### ISSUE TITLE
[Bug]: Next release of AREDN will not have /etc/config/services file

### ISSUE THREAD

**Issue by aanon4** [hickey/meshchat#28]
### Contact Details

tim.j.wilkinson@gmail.com

### Version

nightly build

### System Type

AREDN node

### What happened?

The current nightly build, and next release, of AREDN no longer has the /etc/config/services file. There is a new library - aredn.services - which can be use to fetch this information instead.  As MeshChat uses this file explicitly it will need to handle this change.

Sorry about this - this file was both duplicate information and in the wrong format for where it was stored, so has always been a problem.

**Comment by hickey** [comment]
Thank you for the notification of the upcoming change. 

I am reloading my test node with the current nightly right now to inspect. Is there a timeline as to when this change will hit a release?

**Comment by hickey** [comment]
I am looking that the latest nightly build and not finding anything that looks like it could be the new `aredn.services`. Is there any documentation around this change (even a PR) that you could point me to?

**Comment by hickey** [comment]
Ah, digging around the PRs I was able to find https://github.com/aredn/aredn/pull/1045.
