### ISSUE TITLE
[Bug]Unable to load meshchat v2.1-v2.9 package onto devices running AREDN v3.23.12.0; however, v2.0 will install. 

### ISSUE THREAD

**Issue by convolved-KY4G** [hickey/meshchat#32]
### Contact Details

radiodriven@gmail.com

### Version

v2.0 - v2.9

### System Type

AREDN node

### What happened?

Unable to load meshchat v2.1-v2.9 onto devices running AREDN v3.23.12.0; however, v2.0 will install.

Versions 2.1 through 2.9 give the error shown on the lines below.
Collected errors:

pkg_init_from_file: Malformed package file
/tmp/web/upload/newpkg.ipk.

I tried this on two different GL.iNet AR300M16 nodes and a Mikrotik LDF2 node with the same unsuccessful results.
meshchat_2.0_all.ipk loads fine. Anything newer does not.

![Capture](https://github.com/hickey/meshchat/assets/102929961/c75672bc-7cb5-4b2c-ad82-73b0deffa3cf)

### MeshChat configuration

```
I would gladly do this, but all packages above v2.0 will not load. v2.0 loads fine.
```

### Connection type

Non-connected mesh network

### Node name

KY4G-GO-KIT, KY4G-10-WINLINK, and KY4G-LDF2

### What browsers are you seeing the problem on?

Chrome

**Comment by hickey** [comment]
I had this happen to me as I was testing the final release candidates for the `v2.12.0` release. In my case I was pulling the artifacts from the GitHub Actions runs. They come down as a ZIP file rather than an IPK file. Once I unzipped the file and uploaded the IPK file everything worked as expected. I suspect that you are having the same problem. 

You can use the `file` command on a Linux machine to see the description of the file. Here is both the IPK file and the ZIP file. 

```
❯ file meshchat_20240303-local-config-9de576c_all.ipk
meshchat_20240303-local-config-9de576c_all.ipk: gzip compressed data, from Unix, original size modulo 2^32 81920
❯ file meshchat_20240303-local-config-9de576c_all.ipk.zip
meshchat_20240303-local-config-9de576c_all.ipk.zip: Zip archive data, at least v2.0 to extract, compression method=deflate
```

You should see output like the first command. Where are you finding the old versions of MeshChat?

**Comment by convolved-KY4G** [comment]
So other than some AREDN nodes that I am trying to install these meshchat packages to, I don't have a linux machine handy to try the "file" command on.  These are all *.ipk files and not *.zip files though.  They are only about 349 KB each, so I could email them to you if you wanted them.  I would just need an email address, or perhaps I could upload them here if you would prefer that, but I'd rather let you decide if you want them posted here prior to doing that.  The v2.0 (the one that loads successfully) I downloaded in August 2022 (I'm not sure from where).  The v2.2 (doesn't work) I downloaded in December 2022 (not sure from where).  All of the other versions (except a new file named v2.10 which I downloaded today from https://github.com/kn6plv/meshchat/ and have not tried) were downloaded on January 7, 2024 by going to https://github.com/kn6plv/meshchat/ and navigating to the various tags (e.g. https://github.com/kn6plv/meshchat/tree/v2.4).  There is an API package for each of them there also.  Here is a snapshot of where I've saved the files to.
![Capture](https://github.com/hickey/meshchat/assets/102929961/dff4d95d-d4d0-4407-b242-9f84c4d8241e)

**Comment by hickey** [comment]
Well, I can tell you that they are not IPK files. Way too big for the MeshChat distribution. The MeshChat package is only 60-75KB depending upon which version it is. Even the v2.10 version is twice the size that it should be. I am not sure how you are downloading the files, but either something is being added to the package (have you scanned for malware lately) or the wrong file/packaging is being transferred. You can post one of the files here and I will pull it apart to see that it really is. 

Just off a whim I just tried downloading the ZIP file of the code for the v2.4 tag. It downloaded a 138KB file. Still not the 349KB that most of your files are, but closer to the v2.9 and v2.10 files that you have.

**Comment by convolved-KY4G** [comment]
So, I found a meshchat_2.12.0_all.ipk file on your site (https://github.com/hickey/meshchat/releases/tag/v2.12.0).  It seems to be about the right size and actually installed on the AREDN node just fine.  I'm not sure what these other files were or what was wrong with them.  I will let some other folks that were struggling with the same problem know about the discrepancy and where to download the files now.  Thanks for supporting this project!  It is being used!  You can close this ticket unless you would like me to send you one of the files.
