### ISSUE TITLE
A newcomer to AREDN & MeshChat

### ISSUE THREAD

**Issue by KF0OQA** [hickey/meshchat#33]
Hello,
I'm trying to install MeshChat on DEBIAN which I'm planning to make available over AREDN.  Could you steer me in the right direction?
Thanks,
Pete KF0OQA

**Comment by hickey** [comment]
Currently you will need to install the old Perl version of MeshChat. The last version that was created was `v1.0.2` and can be found on Trevor's website. https://www.trevorsbench.com/meshchat-messaging-for-mesh-networks/

You will also need to install the MeshChat API package on an AREDN node and set the `api_host` variable in the configuration to point to the node on the Debian box. The API package can be downloaded from KN6PLV's repo . https://github.com/kn6plv/meshchat

In an upcoming release the LUA version of MeshChat will be packaged for Debian and at that point the API package will no longer be necessary. I don't have a timeline yet as to when that release will occur, but ikely it will be `v2.12.0`. 

I am going to close this issue, but of you have more questions or need further assistance, please feel free to re-open the issue.
