### ISSUE TITLE
Version number 2.9

### ISSUE THREAD

**Issue by ab7pa** [hickey/meshchat#8]
Gerard, version 2.9 already exists in Tim's repo, so you will want to increment to 2.10 or 3.0 -- whichever you're comfortable with.

**Comment by k1ky** [comment]
There is a MeshChat Channel on the AREDN Slack Workspace. I have made some notes there regarding progress by Gerard.  Would that be an appropriate place to notify the Development Community regarding version progress or what's the plan?

**Comment by ab7pa** [comment]
Gerard, as you know many people have already loaded/installed MeshChat versions 2.9 and 210 from other repositories.  Please consider using version numbers higher than existing -- possibly starting with 3.0 -- so that there will not be confusion over release numbers.  I'm closing this issue, but would encourage you to consider continuity of version numbers.  Thanks.
